### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by joeveiga** [grantila/yaml-diff-patch#3]
## Test 1 (Extra new lines are removed)
```ts
const yaml = `
a: 1



b: 1
`;
const result = yamlOverwrite(yaml, { a: 2, b: 2 });
console.log(result);
```
### Expected
```yaml
a: 2



b: 2
```
### Actual
```yaml
a: 2

b: 2
```

## Test 1 (Empty comments are removed sometimes)
```ts
const yaml = `
a: 1
#
# some doc
#
b: 1
#
c: 1
`;
const result = yamlOverwrite(yaml, { a: 2, b: 2, c: 2 });
console.log(result);
```
### Expected
```yaml
a: 2
#
# some doc
#
b: 2
#
c: 2
```
### Actual
```yaml
a: 2
# some doc
#
b: 2
c: 2
```
